version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432
  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/service
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - db