version: '3'
services:
  app:
    build: .
    volumes:
      - .:/go/src
    ports:
      - "80:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432  